### PR TITLE
ais update

### LINKED ISSUE #720: segfault in MCMC test_infer with multiple threads
Looks like there's some printing in the MCMC code that might be causing a problem with threads.

```
$ echo $JULIA_NUM_THREADS 
4

$ runtests.jl infer
make: Nothing to be done for 'all'.
make: Nothing to be done for 'all'.
make: Nothing to be done for 'all'.
make: Nothing to be done for 'fetch'.
WARNING: Skipping long running tests.  To test everything, run tests with the flag --long-running
Running test_infer.jl
[1]<1> INFO: 18:54:30.806: 614 primary sources, 5 target sources in 164.39, 164.41, 39.11, 39.13

Running AIS on with patch size 
Running AIS on with patch size 
Running AIS on with patch size 
Running AIS on with patch size 
signal (11): Segmentation fault

signal (11): Segmentation fault
while loading /home/kyle/code/Celeste.jl/test/test_infer.jl, in expression starting on line 9
julia: /home/centos/buildbot/slave/package_tarball64/build/deps/srccache/libuv-52d72a52cc7ccd570929990f010ed16e2ec604c8/src/unix/stream.c:956: uv__write_callbacks: Assertion `(((const QUEUE *) (&(stream->loop)->active_reqs) == (const QUEUE *) (*(QUEUE **) &((*(&(stream->loop)->active_reqs))[0]))) == 0)' failed.

signal (6): Aborted
while loading /home/kyle/code/Celeste.jl/test/test_infer.jl, in expression starting on line 9

[...more output...]

Allocations: 22556853 (Pool: 22553469; Big: 3384); GC: 47
Segmentation fault (core dumped)

```

### PR DESCRIPTION
**Pull request by andymiller**
Removes duplicated `write_star_nmgy!` and `write_gal_nmgy!` code (pushed to `fsm_util.jl` and left wrappers w/ the appropriate interface in `Synthetic.jl). 

Added an additional sampling step after AIS to reduce noise in MCMC inferences.

fixes #720

### CODE REVIEW

File: src/Synthetic.jl [hunk 1]
```diff
@@ -14,37 +14,16 @@ using StaticArrays
...
-    p = patches[1]
-    H2, W2 = size(p.active_pixel_bitmap)
-    for w2 in 1:W2, h2 in 1:H2
-        # (h2, w2) index the local patch, while (h, w) index the image
-        h = p.bitmap_offset[1] + h2
-        w = p.bitmap_offset[2] + w2
-        Model.populate_gal_fsm!(fs1m, bvn_derivs, 1, h, w, false, p.wcs_jacobian, gal_mcs)
-        img.pixels[h, w] += fs1m.v[] * ce.gal_fluxes[img.b]
-    end
+    println("writing gal synthetic", typeof(patches))
```
Comment (jeff-regier) [inline src/Synthetic.jl]: Looks like a `println` sneaked in here
