### PR TITLE
Fix type instability in kernels.jl

### LINKED ISSUE #544: ~4-5x slowdown in benchmark_one_light_source on Julia 0.6
In short
### 0.5
```julia
[1]<1> INFO: Done fitting elboargs. Elapsed time: 12.527314414
```
### 0.6
```julia
[1]<1> INFO: Done fitting elboargs. Elapsed time: 56.20631669
```
The timings are recorded on my Mac with Celeste 1ad5402f4f7635568ab10af5e90e75a7b2e00533
See full profile output in https://gist.github.com/andreasnoack/45a11627c198dcb681fc1fbf4961a444

### PR DESCRIPTION
**Pull request by andreasnoack**
Fixes #544

### CODE REVIEW

File: src/deterministic_vi_image_psf/kernels.jl [hunk 1]
```diff
@@ -1,7 +1,7 @@
 
 
 function lanczos_kernel{NumType <: Number}(x::NumType, a::Float64)
-    abs(x) < a ? sinc(x) * sinc(x / a): zero(NumType)
+    abs(x) < a ? sinc(x) * sinc(x / a) : zero(promote_type(NumType, Float64))
```
Comment (Keno) [inline src/deterministic_vi_image_psf/kernels.jl:4]: `a * zero(NumType)`?
